services:
  - type: web
    name: info-health-api
    runtime: docker
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
